# $FreeBSD$

PORTNAME=	cipier
PORTVERSION=	1.5
CATEGORIES=	devel

MAINTAINER=	koue@chaosophia.net
COMMENT=	FreeBSD Continuous Integration Framework for Github

LICENSE=	BSD3CLAUSE

WRKSRC_SUBDIR=	src/

USE_GITHUB=	yes
GH_ACCOUNT=	koue
GH_PROJECT=	cipier

.include <bsd.port.mk>
